import axios from "axios";
import Articles from "components/organisms/Articles/Articles";
import TradingTable from "components/organisms/TradingTable/TradingTable";
import { errorFactory } from "lib/utils/errorHandlers";
import Head from "next/head";

export async function getStaticProps() {
  let articles = null;
  const error = { isError: false, error: null };

  try {
    const articleRes = await axios.get(
      `${process.env.NEXT_PUBLIC_STRAPI_URL}/articles`
    );
    articles = articleRes.data;
  } catch (e) {
    error.isError = true;
    error.error = errorFactory(e);
  }

  return {
    props: { articles, error },
  };
}

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>Public Trader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{"Today's Cryptocurrency Prices"}</h1>
      <TradingTable />

      <Articles data={articles.data} />
    </>
  );
}
